version: "3.8"

services:
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        container_name: calendar-app-db
        environment:
            MYSQL_ROOT_PASSWORD: mysql       
        ports:
            - 3306:3306
        volumes:
            - ./db-data-volume:/var/lib/mysql
    migration:
        image: flyway/flyway
        depends_on:
            - db
        container_name: calendar-app-migration
        volumes:
            - ./database/migration/schema:/flyway/sql
