version: "3.8"

services:
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        container_name: calendar-app-db
        environment:
            MYSQL_ROOT_PASSWORD: mysql       
        ports:
            - 3306:3306
        security_opt:
            - seccomp:unconfined
        volumes:
            - ./db-data-volume:/var/lib/mysql
    migration:
        image: flyway/flyway
        depends_on:
            - db
        container_name: calendar-app-migration
        volumes:
            - ./database/migration/schema:/flyway/sql

    backend-api:
        build:
            context: ./backend
        command: reflex -r '\.go$$' -s -- sh -c 'go run main.go -databaseDatasource="${DATABASE_DATASOURCE}" -serviceAccountKeyPath=/tmp/serviceAccount.json -port=8080'
        container_name: calendar-app-api
        ports:
            - 1989:1989
        volumes:
            - ./backend:/usr/local/go/src/app
            - ${GOOGLE_APPLICATION_CREDENTIALS}:/tmp/serviceAccount.json
        working_dir: /usr/local/go/src/app

